name: CodeIgniter 3 Deployment

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    # Checkout repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Setup PHP environment
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.1  # Sesuaikan dengan versi PHP Anda
        extensions: mbstring, intl, mysqli
        ini-values: post_max_size=256M, upload_max_filesize=256M
        coverage: none

    # Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
